# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: version-check
    name: version-check
    language: python
    additional_dependencies: [requests]
    entry: python -c 'from tests.test_version import test_local_against_pypi_version; test_local_against_pypi_version()'

# Python linter (Flake8)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8

# Python formatting
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

# Python type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.812'
  hooks:
  - id: mypy
